# Generated by Django 4.2.11 on 2024-06-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_mymodelpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
