# Generated by Django 4.2.11 on 2024-06-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='', editable=False, max_length=150),
            preserve_default=False,
        ),
    ]
