# Generated by Django 4.2.11 on 2024-06-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0006_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
